repos:
  - repo: local
    hooks:
      - &custom
        id: custom
        name: custom
        entry: custom
        language: python
        types: [python]
      - <<: *custom
        args: ['something']
      - <<: *custom
        args: ['something-else']